import type { Metadata } from "next"
import localFont from "next/font/local"
import "@/styles/globals.css"
import AppProvider from '@/providers/AppProvider'
import { Toaster } from '@/components/ui/toaster'
import { Toast, ToastProvider } from '@/components/ui/toast'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode
}>)
{
  return (
    <html lang="en" className='h-full'>
      <body
        className={ `${ geistSans.variable } ${ geistMono.variable } antialiased h-full` }
      >
        <Toaster />
        <AppProvider>
          { children }
        </AppProvider>
      </body>
    </html>
  )
}
